### PR TITLE
Updated and rewritten the package and also tested it!

### PR DESCRIPTION
**Pull request by TejasLamba2006**

### CODE REVIEW

**Comment by TheGamer3514** [comment]
Does not follow old structure, there are conflicts and it was tested on an old version of js. Should have been tested on multiple versions

**Comment by TheGamer3514** [comment]
Also incorrectly did credits (Ishaan did not originally make)

**Comment by TejasLamba2006** [comment]
Hey, @ishaantek , quit stallin' and merge that pull req pronto. Ain't no time for conflicts, unless you wanna hear some chump kids yammerin' on with their nonsense comments.

**Comment by TheGamer3514** [comment]
Contains too much useless code

**Comment by TheGamer3514** [comment]
also no optional way of inputting shard count

**Comment by TheGamer3514** [comment]
you also set the author as "The universe botlist team". Surely you would put "Ishaan Garg"

**Comment by TheGamer3514** [comment]
you also did not change the version

**Pull request merged**
